#!/usr/bin/env python3
"""
Generate a Quarto website for the DiAgnostiK course catalog.

This script reads course metadata and produces the dynamic parts of the
Quarto project under quarto/:
  quarto/index.qmd        - Landing page with one card per category
  quarto/<slug>.qmd       - One page per category listing course cards

The static parts (quarto/_quarto.yml, quarto/styles.css, quarto/icon.ico)
are committed directly to the repository and are not generated by this script.

Run `quarto render quarto/` afterwards to build the HTML into docs/.

Key improvement over the old LiaScript-exporter approach:
  A course that matches multiple category tags is included on every
  matching category page (no clone_cards.py workaround needed).
"""

import os
import re
import sys
import logging
from pathlib import Path
from collections import defaultdict

from generate_project_yaml import (
    YamlCommentParser,
    find_markdown_files,
    load_additional_courses,
    create_external_dict,
    get_url,
    is_url,
    to_github_tag,
    tag_exists,
    CATEGORY_LIST,
    ADDITIONALS,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

LIASCRIPT_BASE = "https://liascript.github.io/course/?"
RELEASES_BASE = "https://github.com/Ifi-DiAgnostiK-Project/LiaScript-Courses/releases/download"
COURSES_RAW_BASE = (
    "https://raw.githubusercontent.com/Ifi-DiAgnostiK-Project/LiaScript-Courses"
    "/refs/heads/main/courses/"
)
QUARTO_DIR = Path("quarto")

logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")


# ---------------------------------------------------------------------------
# Helper utilities
# ---------------------------------------------------------------------------


def category_to_slug(category: str) -> str:
    """Return a URL-friendly slug for a category name.

    Examples:
        'Tischler'                      -> 'tischler'
        'Arbeits-_und_Gesundheitsschutz' -> 'arbeits-und-gesundheitsschutz'
    """
    slug = category.lower().replace("_", "-")
    slug = re.sub(r"[^a-z0-9-]", "-", slug)
    slug = re.sub(r"-{2,}", "-", slug).strip("-")
    return slug


def category_display_name(category: str) -> str:
    """Return a human-readable name for a category."""
    return category.replace("_und_", " und ").replace("_", " ")


def get_all_categories(metadata: dict) -> list:
    """Return every CATEGORY_LIST entry matched by the course's tags.

    Unlike ``categorize_file`` in generate_project_yaml.py, this function
    returns *all* matching categories so that a course can appear on multiple
    category pages without any post-processing workaround.
    """
    tags = metadata.get("tags", [])
    if isinstance(tags, str):
        tags = [tags]
    elif not tags:
        tags = []
    tags_lower = {t.lower() for t in tags}
    matched = [cat for cat in CATEGORY_LIST[:-1] if cat.lower() in tags_lower]
    return matched if matched else ["Sonstige"]


def resolve_logo(logo: str) -> str:
    """Return an absolute URL for a course logo.

    Logo paths in course metadata are sometimes relative (e.g. ``img/foo.jpg``),
    meaning they are relative to the ``courses/`` directory.  This function
    converts those relative paths to absolute GitHub raw content URLs so that
    the generated Quarto pages can display the images correctly.
    """
    if not logo or is_url(logo):
        return logo
    # Treat as a path relative to the courses/ directory
    return COURSES_RAW_BASE + logo.lstrip("/")



def get_release_urls(file_path, version: str) -> dict:
    """Return GitHub release download URLs for a locally-hosted course file.

    Returns an empty dict when the file is an external URL, the version is
    missing, or the corresponding git tag does not yet exist.
    """
    if not version or is_url(file_path):
        return {}

    file_path = Path(file_path)
    tag_name = f"{to_github_tag(file_path)}_v{version}"
    if not tag_exists(tag_name):
        return {}

    base_name = file_path.stem
    url_base = f"{RELEASES_BASE}/{base_name.lower()}_v{version.lower()}/{base_name}_v{version}"
    return {
        "PDF": f"{url_base}_Documentation.pdf",
        "SCORM": f"{url_base}_SCORM.zip",
    }


# ---------------------------------------------------------------------------
# Course data collection
# ---------------------------------------------------------------------------


def build_course_data(files: list, external_dict: dict) -> dict:
    """Parse all course files and organise them by category.

    Returns a ``defaultdict(list)`` mapping category name → list of course
    dicts.  A course that matches multiple categories is included in each.
    """
    categories: dict = defaultdict(list)
    parser = YamlCommentParser()

    for file in files:
        meta = parser.parse(str(file))
        if not meta:
            continue

        title = meta.get("title") or (
            Path(file).stem if not is_url(file) else str(file)
        )
        comment = meta.get("comment", "")
        logo = resolve_logo(meta.get("logo", ""))
        tags = meta.get("tags", [])
        if isinstance(tags, str):
            tags = [tags]
        elif not tags:
            tags = []
        version = meta.get("version")

        tagged = external_dict.get(file, False)
        url = get_url(file, version, tagged=tagged)
        release_urls = get_release_urls(file, version) if tagged else {}

        course = {
            "title": title,
            "comment": comment,
            "logo": logo,
            "tags": tags,
            "url": url,
            "release_urls": release_urls,
        }

        for cat in get_all_categories(meta):
            categories[cat].append(course)
            logging.info("Added '%s' to category '%s'", title, cat)

    return categories


# ---------------------------------------------------------------------------
# Quarto file writers
# ---------------------------------------------------------------------------


def write_index_page(categories: dict, output_dir: Path) -> None:
    """Write ``index.qmd`` – the landing page with one card per category."""
    lines = [
        "---",
        'title: "DiAgnostiK Lehr- und Lernraum"',
        "listing: false",
        "---",
        "",
        "![](https://raw.githubusercontent.com/vgoehler/DiAgnostiK_LiaScript/refs/heads/main/img/slogan_hero.png){.hero-image width=100%}",
        "",
        "## Kurs-Kategorien",
        "",
        "Wählen Sie eine Kategorie, um die entsprechenden Kurse anzusehen:",
        "",
        ":::: {.grid}",
        "",
    ]

    for cat in CATEGORY_LIST:
        courses = categories.get(cat, [])
        if not courses:
            continue
        slug = category_to_slug(cat)
        display = category_display_name(cat)
        count = len(courses)
        plural = "e" if count != 1 else ""
        lines += [
            "::: {.g-col-12 .g-col-md-6 .g-col-lg-4}",
            "::: {.card .h-100}",
            "::: {.card-body}",
            f"### [{display}]({slug}.qmd)",
            "",
            f"*{count} Kurs{plural}*",
            ":::",
            ":::",
            ":::",
            "",
        ]

    lines += ["::::", ""]

    (output_dir / "index.qmd").write_text("\n".join(lines), encoding="utf-8")
    logging.info("Written index.qmd")


def write_category_page(category: str, courses: list, output_dir: Path) -> None:
    """Write ``<slug>.qmd`` with a card for every course in the category."""
    slug = category_to_slug(category)
    display = category_display_name(category)

    lines = [
        "---",
        f'title: "{display}"',
        "---",
        "",
        ":::: {.grid}",
        "",
    ]

    for course in courses:
        title = course["title"]
        comment = course.get("comment", "")
        logo = course.get("logo", "")
        tags = course.get("tags", [])
        url = course["url"]
        release_urls = course.get("release_urls", {})
        liascript_link = f"{LIASCRIPT_BASE}{url}"

        lines += [
            "::: {.g-col-12 .g-col-md-6 .g-col-lg-4}",
            "::: {.card .h-100}",
        ]

        if logo:
            lines.append(f"![{title}]({logo}){{.card-img-top}}")

        lines += [
            "::: {.card-body}",
            f"#### [{title}]({liascript_link}){{target='_blank'}}",
        ]

        if comment:
            lines += ["", comment, ""]

        if tags:
            badges = " ".join(f"`{t}`" for t in tags)
            lines += ["", badges, ""]

        lines.append(":::")  # /card-body

        if release_urls:
            lines.append("::: {.card-footer}")
            link_parts = []
            if "PDF" in release_urls:
                link_parts.append(
                    f"[📄 PDF]({release_urls['PDF']}){{target='_blank'}}"
                )
            if "SCORM" in release_urls:
                link_parts.append(
                    f"[📦 SCORM]({release_urls['SCORM']}){{target='_blank'}}"
                )
            lines.append(" &nbsp; ".join(link_parts))
            lines.append(":::")  # /card-footer

        lines += [
            ":::",  # /card
            ":::",  # /g-col
            "",
        ]

    lines += ["::::", ""]

    (output_dir / f"{slug}.qmd").write_text("\n".join(lines), encoding="utf-8")
    logging.info("Written %s.qmd", slug)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    logging.info("Generating Quarto website sources…")

    files = list(find_markdown_files())
    adds = load_additional_courses(ADDITIONALS)
    all_files = files + adds
    external_dict = create_external_dict(all_files, adds)

    categories = build_course_data(all_files, external_dict)

    QUARTO_DIR.mkdir(parents=True, exist_ok=True)

    write_index_page(categories, QUARTO_DIR)

    # Generate a page for every category in CATEGORY_LIST so that the static
    # _quarto.yml navbar references are always satisfied, even for categories
    # that currently have no courses (those pages will just show an empty grid).
    for cat in CATEGORY_LIST:
        write_category_page(cat, categories.get(cat, []), QUARTO_DIR)

    logging.info("Quarto sources written to %s/", QUARTO_DIR)


if __name__ == "__main__":
    main()
