project:
  type: website
  output-dir: ../docs

website:
  title: DiAgnostiK Lehr- und Lernraum
  description: Sammlung aller Kurse des DiAgnostik Projekts
  favicon: icon.ico
  navbar:
    logo: https://raw.githubusercontent.com/vgoehler/DiAgnostiK_LiaScript/refs/heads/main/img/Logo_234px.png
    title: DiAgnostiK
    left:
      - text: Tischler
        href: tischler.qmd
      - text: SHK
        href: shk.qmd
      - text: Zahntechniker
        href: zahntechniker.qmd
      - text: Maler
        href: maler.qmd
      - text: Raumausstatter
        href: raumausstatter.qmd
      - text: Belehrung
        href: belehrung.qmd
      - text: Arbeits- und Gesundheitsschutz
        href: arbeits-und-gesundheitsschutz.qmd
      - text: Umfragen
        href: umfragen.qmd
      - text: Wissensspeicher
        href: wissensspeicher.qmd
      - text: Experimente
        href: experimente.qmd
      - text: Sonstige
        href: sonstige.qmd
  page-footer:
    center: "Besuchen Sie uns auf unserer Webseite: [https://uelu-digital.de](https://uelu-digital.de)"
    right:
      - text: "Gefördert durch"
      - text: "<img src='/assets/Kombi-EU-SN-horizontal.jpg' style='height:50px;'>"
      - text: "Unsere Partner:"
      - text: |
          <a href='https://www.gkz-ev.de/'><img src='/assets/gkz.jpg' style='height:50px; margin-right:10px;'></a>
          <a href='https://www.hwk-dresden.de'><img src='/assets/hwk.png' style='height:50px; margin-right:10px;'></a>
          <a href='https://tu-freiberg.de/'><img src='/assets/tubaf.png' style='height:50px;'></a>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
